import streamlit as st
import google.generativeai as genai
import os

# 1. SETUP: Configure the API Key
try:
    genai.configure(api_key=st.secrets["GOOGLE_API_KEY"])
except Exception as e:
    st.error("API Key not found. Please set it in Streamlit Secrets.")

# 2. UI: Page Configuration
st.set_page_config(page_title="Cuisine Finder", page_icon="🍽️", layout="wide")

# Custom CSS
st.markdown("""
    <style>
    .stButton>button {
        background-color: #E63946;
        color: white;
        border-radius: 20px;
        width: 100%;
        font-weight: bold;
    }
    /* Style for the links in the table */
    a {
        text-decoration: none;
        color: #1E88E5 !important; 
        font-weight: bold;
    }
    a:hover {
        text-decoration: underline;
        color: #0D47A1 !important;
    }
    </style>
    """, unsafe_allow_html=True)

# 3. APP HEADER
st.title("🍽️ Global Food Hunter")
st.markdown("Search for specific dishes (e.g., **Laksa, Burgers, Sushi**) or Cuisines in any neighborhood.")

# 4. FILTERS
col1, col2 = st.columns(2)

with col1:
    # CHANGED: Replaced Selectbox with Text Input for flexibility
    food_search = st.text_input(
        "What are you craving?", 
        placeholder="e.g. Japanese, Burgers, Laksa, Dim Sum..."
    )

with col2:
    budget = st.select_slider(
        "Select Budget",
        options=['Any', '$ (Cheap)', '$$ (Moderate)', '$$$ (Expensive)', '$$$$ (Luxury)']
    )

# 5. INPUT: Location
location = st.text_input("Where are you looking?", placeholder="e.g. Tampines, Orchard, Shibuya, NYC...")

# 6. LOGIC: The Search Button
if st.button("Find Top Recommendations"):
    if not location or not food_search:
        st.warning("Please enter both a food type and a location.")
    else:
        try:
            # FIXED: 'gemini-2.5-pro' does not exist yet. 
            # We use 'gemini-1.5-flash' for speed or 'gemini-1.5-pro' for better reasoning.
            model = genai.GenerativeModel('gemini-1.5-flash')
            
            # IMPROVED PROMPT:
            # 1. Strict Geofencing to stop showing Orchard results for Tampines searches.
            # 2. Dynamic food insertion.
            prompt = f"""
            Act as a local food expert.
            I am looking for: "{food_search}" 
            Location: "{location}"
            Budget Level: "{budget}"
            
            Task:
            List the TOP 20 highest-rated places that fit these criteria.
            
            CRITICAL RULES:
            1. GEOGRAPHY: The restaurants MUST be physically located INSIDE or immediately adjacent to "{location}". Do NOT suggest places in the city center if the user asked for a specific suburb (e.g., if user asks for Tampines, DO NOT show Orchard Road restaurants).
            2. QUANTITY: Try to find 20. If there are not 20 valid high-rated places strictly in {location}, list as many as possible (e.g., Top 10) rather than inventing fake ones or showing places far away.
            3. LINKING: Format the Name as a Markdown Link that searches Google.
               Format: [Restaurant Name](https://www.google.com/search?q=Restaurant+Name+{location}+Food)
            
            Output Format:
            Provide a Markdown Table with these columns:
            | Restaurant Name | Price | Rating (Estimate) | Best Dish to Order | Why it's good |
            
            """
            
            with st.spinner(f"Hunting for the best {food_search} in {location}..."):
                response = model.generate_content(prompt)
                
            # Show results
            if response.text:
                st.markdown("### Top Recommendations")
                st.markdown(response.text)
                st.caption(f"Note: Results are generated by AI based on popular ratings in {location}.")
            else:
                st.error("No response generated. Please try again.")
            
        except Exception as e:
            st.error(f"An error occurred. Check your API Key or Connection. Error: {e}")


